{% set name = "types-protobuf" %}
{% set version = "6.30.2.20250822" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: faacbbe87bd8cba4472361c0bd86f49296bd36f7761e25d8ada4f64767c1bde9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

test:
  files:
    - _run_test.py
  commands:
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi  # [not win]
    - if not exist %SP_DIR%\\google-stubs\\protobuf\\__init__.pyi exit 1  # [win]
    - pip check
  requires:
    - pip
    - protobuf
    - types-futures

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for protobuf
  license: Apache-2.0 AND MIT
  license_family: Apache
  license_file: LICENSE
  doc_url: https://typing.readthedocs.io/
  dev_url: https://github.com/python/typeshed
  description: |
    This is a PEP 561 type stub package for the protobuf package.
    It can be used by type-checking tools like mypy, pyright, pytype, Pyre, PyCharm, etc. to check code that uses protobuf.
    This version of types-protobuf aims to provide accurate annotations for protobuf~=5.29.1.



extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
