{% set name = "types-protobuf" %}
{% set version = "4.21.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-protobuf-{{ version }}.tar.gz
  sha256: 819a7c67e69476e39c3f0c9871bbb9ee82313645d317b6daeb60ac95a309dbd3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  #[py<36]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - types-futures

test:
  commands:
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi


about:
  home: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io/
  summary: Typing stubs for protobuf
  description: |
    This is a PEP 561 type stub package for the protobuf package. 
    It can be used by type-checking tools like mypy, pyright, 
    pytype, PyCharm, etc. to check code that uses protobuf.
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  licence_family: Apache

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
