{% set name = "types-protobuf" %}
{% set version = "4.25.0.20240417" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-protobuf-{{ version }}.tar.gz
  sha256: c34eff17b9b3a0adb6830622f0f302484e4c089f533a46e3f147568313544352

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  #[py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - types-futures

test:
  files:
    - _run_test.py
  requires:
    - pip
    - protobuf
  commands:
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi  # [not win]
    - if not exist %SP_DIR%\\google-stubs\\protobuf\\__init__.pyi exit 1 # [win]
    - pip check


about:
  home: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io/
  summary: Typing stubs for protobuf
  description: |
    This is a PEP 561 type stub package for the protobuf package. 
    It can be used by type-checking tools like mypy, pyright, 
    pytype, PyCharm, etc. to check code that uses protobuf.
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
