{% set name = "types-protobuf" %}
{% set version = "3.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-protobuf-{{ version }}.tar.gz
  sha256: 1d3e5137ca4dc602e9fc30c2dc116def3e32f87884c56c4fb7122b20e9e8ba81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-futures

test:
  commands:
    - test -f $SP_DIR/google-stubs/__init__.pyi
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for protobuf
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
